# This file was generated by GoReleaser. DO NOT EDIT.
cask "realm" do
  name "realm"
  desc "Inheritable and overridable configuration management"
  homepage "https://github.com/steviebps/realm"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "realm"

  on_macos do
    on_intel do
      url "https://github.com/steviebps/realm/releases/download/v#{version}/realm_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "789044773d16b395dd07c6a0f337366242a9d423aea403089ab25d6d033e606d"
    end
    on_arm do
      url "https://github.com/steviebps/realm/releases/download/v#{version}/realm_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "fb89518dc7c5b7f598083b29e1ef34f80e3193d8d9e25761e43050bb8b45e038"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/steviebps/realm/releases/download/v#{version}/realm_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "c4d5da284c0ba90c69f2193ef21994e3464e2b6bcb7016592f56363175b480fc"
    end
    on_arm do
      url "https://github.com/steviebps/realm/releases/download/v#{version}/realm_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "77f6c53d89dc57d2f359ced6995b85bda46b38cecf8d347a86ace1c484de38d9"
    end
  end

  # No zap stanza required
end
