# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RealmAT0020 < Formula
  desc "Inheritable and overridable configuration management "
  homepage "https://github.com/steviebps/realm"
  version "0.0.20-pre.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.1/realm_0.0.20-pre.1_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e853a181a20732a681f88f76b43d591de09ca3583e000ce05d019c024b3d5313"

      def install
        bin.install "realm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.1/realm_0.0.20-pre.1_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d92e9347df252fe9e78e49ce4b2e42a93b6d86a229f4707cd0506285c193bed0"

      def install
        bin.install "realm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.1/realm_0.0.20-pre.1_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "878ee9723b5c1af983614bee88be2166998f78c59e508adb021f1685e5b03099"

      def install
        bin.install "realm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.1/realm_0.0.20-pre.1_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "56d9e8778cedfa1aedd1efbbcf0386d596503b838c5a57907717ad3cc5943c15"

      def install
        bin.install "realm"
      end
    end
  end
end
