# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Realm < Formula
  desc "Inheritable and overridable configuration management"
  homepage "https://github.com/steviebps/realm"
  version "0.0.20"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20/realm_0.0.20_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3ac7cecb2dc4869177ab325f8108090b9ac0c28c662582e3efc84e8a2af7b9da"

      def install
        bin.install "realm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20/realm_0.0.20_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cdd78d64057201e0235a94bd1102565795e6caf9d97339180742facac4034b19"

      def install
        bin.install "realm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20/realm_0.0.20_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8030c357d7148bb7be57d8e5cb89258ee2320aabea5571a00f5e624f9447d007"

      def install
        bin.install "realm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20/realm_0.0.20_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6892c7aecba99ce23d4457e26183cd0d6721e774dade0098fa0c59843eb7798a"

      def install
        bin.install "realm"
      end
    end
  end
end
